[2023-05-13T10:10:56.710+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: qiberry.delete_table manual__2023-05-13T10:10:53.048357+00:00 [queued]>
[2023-05-13T10:10:56.732+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: qiberry.delete_table manual__2023-05-13T10:10:53.048357+00:00 [queued]>
[2023-05-13T10:10:56.734+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-05-13T10:10:56.776+0000] {taskinstance.py:1350} INFO - Executing <Task(PostgresOperator): delete_table> on 2023-05-13 10:10:53.048357+00:00
[2023-05-13T10:10:56.788+0000] {standard_task_runner.py:57} INFO - Started process 315 to run task
[2023-05-13T10:10:56.802+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'qiberry', 'delete_table', 'manual__2023-05-13T10:10:53.048357+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag_laba3.py', '--cfg-path', '/tmp/tmp66vgz8ir']
[2023-05-13T10:10:56.806+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask delete_table
[2023-05-13T10:10:56.945+0000] {task_command.py:410} INFO - Running <TaskInstance: qiberry.delete_table manual__2023-05-13T10:10:53.048357+00:00 [running]> on host bfb86d9b8782
[2023-05-13T10:10:57.075+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='qiberry' AIRFLOW_CTX_TASK_ID='delete_table' AIRFLOW_CTX_EXECUTION_DATE='2023-05-13T10:10:53.048357+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-13T10:10:53.048357+00:00'
[2023-05-13T10:10:57.079+0000] {sql.py:262} INFO - Executing: 
        DROP TABLE public.planes
        
[2023-05-13T10:10:57.095+0000] {base.py:73} INFO - Using connection ID 'qiberry' for task execution.
[2023-05-13T10:10:57.269+0000] {base.py:73} INFO - Using connection ID 'qiberry' for task execution.
[2023-05-13T10:10:57.283+0000] {sql.py:375} INFO - Running statement: 
        DROP TABLE public.planes
        , parameters: None
[2023-05-13T10:10:57.290+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 274, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: table "planes" does not exist

[2023-05-13T10:10:57.320+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=qiberry, task_id=delete_table, execution_date=20230513T101053, start_date=20230513T101056, end_date=20230513T101057
[2023-05-13T10:10:57.352+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 7 for task delete_table (table "planes" does not exist
; 315)
[2023-05-13T10:10:57.412+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-13T10:10:57.522+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
