[2023-05-13T10:39:44.907+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: qiberry.create_table_people manual__2023-05-13T10:30:44.926226+00:00 [queued]>
[2023-05-13T10:39:45.110+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: qiberry.create_table_people manual__2023-05-13T10:30:44.926226+00:00 [queued]>
[2023-05-13T10:39:45.118+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-05-13T10:39:45.423+0000] {taskinstance.py:1350} INFO - Executing <Task(PostgresOperator): create_table_people> on 2023-05-13 10:30:44.926226+00:00
[2023-05-13T10:39:45.463+0000] {standard_task_runner.py:57} INFO - Started process 74 to run task
[2023-05-13T10:39:45.550+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'qiberry', 'create_table_people', 'manual__2023-05-13T10:30:44.926226+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/dag_laba3.py', '--cfg-path', '/tmp/tmpssopq8h1']
[2023-05-13T10:39:45.613+0000] {standard_task_runner.py:85} INFO - Job 29: Subtask create_table_people
[2023-05-13T10:39:47.073+0000] {task_command.py:410} INFO - Running <TaskInstance: qiberry.create_table_people manual__2023-05-13T10:30:44.926226+00:00 [running]> on host bfb86d9b8782
[2023-05-13T10:39:48.362+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='qiberry' AIRFLOW_CTX_TASK_ID='create_table_people' AIRFLOW_CTX_EXECUTION_DATE='2023-05-13T10:30:44.926226+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-13T10:30:44.926226+00:00'
[2023-05-13T10:39:48.388+0000] {sql.py:262} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS public.people (
            firstname varchar,
            lastname varchar,
            age int,
            sex varchar,
            color varchar
        );
        
[2023-05-13T10:39:48.452+0000] {base.py:73} INFO - Using connection ID 'qiberry' for task execution.
[2023-05-13T10:39:48.996+0000] {base.py:73} INFO - Using connection ID 'qiberry' for task execution.
[2023-05-13T10:39:49.023+0000] {sql.py:375} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS public.people (
            firstname varchar,
            lastname varchar,
            age int,
            sex varchar,
            color varchar
        );
        , parameters: None
[2023-05-13T10:39:49.062+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 274, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(people, 2200) already exists.

[2023-05-13T10:39:49.104+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=qiberry, task_id=create_table_people, execution_date=20230513T103044, start_date=20230513T103944, end_date=20230513T103949
[2023-05-13T10:39:49.186+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 29 for task create_table_people (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(people, 2200) already exists.
; 74)
[2023-05-13T10:39:49.247+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-13T10:39:49.369+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
